#!/bin/bash
#PBS -q dssc
#PBS -l nodes=1:ppn=48
#PBS -l walltime=00:03:00

cd $PBS_O_WORKDIR

rm mpi.script.*
rm out.mpi out.time.mpi
 
module load   openmpi/4.0.3/gnu/9.3.0

MOVES="100000000" 

for procs in 1 4 8 12 16 20 24 28 32 36 40 44 48 ; do
echo "executing on ", ${procs}, "  processors" 
/usr/bin/time mpirun  --mca btl '^openib' -np ${procs} my_mpi_pi.x  ${MOVES} >>out.mpi 2>>out.time.mpi
done 
