#!/bin/bash
#PBS -q dssc
#PBS -l nodes=ct1pf-fnode001:ppn=24+:ct1pf-fnode002:ppn=24+:ct1pf-fnode003:ppn=24+:ct1pf-fnode004:ppn=24+:ct1pf-fnode005:ppn=24+:ct1pf-fnode006:ppn=24
#PBS -l walltime=12:00:00

cd $PBS_O_WORKDIR

rm s_scal_new.*
 
module load  openmpi/4.0.3/gnu/9.3.0


for procs in 1 12 24 48 72 96 120 144; do
mpirun --mca btl '^openib' -np ${procs} blur_mpi.x earth-large.pgm 11 1 0.2 >>time_strong_new_mpi11
done


for threads in 1 12 24 48 72 96 120 144; do
./blur_opm.x ${threads} earth-large.pgm 11 1 0.2 >>time_strong_new_opm11
done
