#!/bin/bash
#PBS -q dssc
#PBS -l nodes=1:ppn=48
#PBS -l walltime=48:00:00

cd $PBS_O_WORKDIR

rm strong_scal.*
 
module load  openmpi/4.0.3/gnu/9.3.0


for procs in 1 4 8 12 16 20 24 28 32 36 40 44 48 ; do
mpirun --mca btl '^openib' -np ${procs} blur_mpi.x earth-large.pgm 101 1 0.2 >>time_strong_earth_mpi101
done


for threads in 1 4 8 12 16 20 24 28 32 36 40 44 48 96 144 192; do
./blur_opm.x ${threads} earth-large.pgm 101 1 0.2 >>time_strong_earth_opm101
done
