#!/bin/bash
#PBS -q dssc
#PBS -l nodes=1:ppn=48
#PBS -l walltime=03:00:00

cd $PBS_O_WORKDIR

rm strong_scal.*
rm time_strong_mpi
rm time_strong_opm
 
module load  openmpi/4.0.3/gnu/9.3.0


for procs in 1 4 8 12 16 20 24 28 32 36 40 44 48 ; do
mpirun --mca btl '^openib' -np ${procs} blur_mpi.x check_me.pgm 99 0 >>time_strong_mpi
done


for threads in 1 4 8 12 16 20 24 28 32 36 40 44 48 96 144 192; do
blur_opm.x ${threads} check_me.pgm 99 0 >>time_strong_opm
done
